application: pintheworld-146615
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /api/.*
  script: main.app

- url: (.*)/
  static_files: webapp\1/index.html
  upload: webapp

- url: (.*)
  static_files: webapp\1
  upload: webapp
